version: "3"
services:
  hub:
    image: selenium/hub:4.15.0
    
  chrome:
    image: selenium/node-chrome:4.15.0
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.15.0
    shm_size: '2g'
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  cucumbertestcases:
    image: attbatch1/buildimagthroughjenkins
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=hub
    volumes:
      - ./testcaseoutputfolder/cucumberreport:/home/selenium-docker/target/cucumber-reports



  